---
model_type:
  type: array
  array_type: str
  values:
    - yolo12s.pt
epochs:
  type: space
  space_type: int
  space_config:
    type: linear
    start: 50
    stop: 70
    num: 10
patience:
  type: space
  space_type: int
  space_config:
    type: linear
    start: 10
    stop: 50
    num: 10
batch:
  type: array
  array_type: int
  values:
    - -1
imgsz:
  type: array
  array_type: int
  values:
    - 1024
optimizer:
  type: array
  array_type: str
  values:
    - SGD
    - Adam
    - AdamW
    - NAdam
    - RAdam
    - RMSProp
    - auto
lr0:
  type: space
  space_type: float
  space_config:
    type: logarithmic
    base: 10
    start: 0.0001
    stop: 0.03
    num: 50
lrf:
  type: space
  space_type: float
  space_config:
    type: logarithmic
    base: 10
    start: 0.001
    stop: 0.01
    num: 50
box:
  type: array
  array_type: float
  values:
    - 0.5
    - 3
    - 7.5
cls:
  type: array
  array_type: float
  values:
    - 0.5
    - 2
dfl:
  type: array
  array_type: float
  values:
    - 0.5
    - 1.5
# Data Augmentation
mixup:
  type: array
  array_type: float
  values:
    - 0
    - 0.2
close_mosaic:
  type: space
  space_type: int
  space_config:
    type: linear
    start: 0.
    stop: 35.
    num: 10
degrees:
  type: space
  space_type: float
  space_config:
    type: linear
    start: 0.
    stop: 10.
    num: 10
translate:
  type: space
  space_type: float
  space_config:
    type: linear
    start: 0
    stop: 0.4
    num: 10
