---
stages:
  build_model_input:
    cmd:
      - >-
        uv run python ./scripts/data/model_input/build.py
        --input-dir ./data/01_raw/wildfire
        --output-dir ./data/03_model_input/wildfire/
        --random-seed 0
        --sampling-ratio 0.05
        --loglevel info
    deps:
      - ./scripts/data/model_input/build.py
      - ./data/01_raw/wildfire
    outs:
      - ./data/03_model_input/wildfire/

  train_yolo_baseline_small:
    cmd:
      - >-
        uv run python ./scripts/model/yolo/train.py
        --data ./data/03_model_input/wildfire/small/datasets/data.yaml
        --config ./scripts/model/yolo/configs/baseline.yaml
        --output-dir ./data/04_models/yolo/
        --experiment-name baseline_small
        --loglevel info
    deps:
      - ./scripts/model/yolo/train.py
      - ./scripts/model/yolo/configs/baseline.yaml
      - ./data/03_model_input/wildfire/small/
    outs:
      - ./data/04_models/yolo/baseline_small/

  train_yolo_baseline:
    cmd:
      - >-
        uv run python ./scripts/model/yolo/train.py
        --data ./data/03_model_input/wildfire/full/datasets/data.yaml
        --config ./scripts/model/yolo/configs/baseline.yaml
        --output-dir ./data/04_models/yolo/
        --experiment-name baseline_full
        --loglevel info
    deps:
      - ./scripts/model/yolo/train.py
      - ./scripts/model/yolo/configs/baseline.yaml
      - ./data/03_model_input/wildfire/full/datasets/
    outs:
      - ./data/04_models/yolo/baseline_full

  train_yolo_best:
    cmd:
      - >-
        uv run python ./scripts/model/yolo/train.py
        --data ./data/03_model_input/wildfire/full/datasets/data.yaml
        --config ./scripts/model/yolo/configs/best.yaml
        --output-dir ./data/04_models/yolo/
        --experiment-name best
        --loglevel info
    deps:
      - ./scripts/model/yolo/train.py
      - ./scripts/model/yolo/configs/best.yaml
      - ./data/03_model_input/wildfire/full/datasets/
    outs:
      - ./data/04_models/yolo/best

  build_manifest_yolo_best:
    cmd:
      - >-
        uv run python ./scripts/model/yolo/build_manifest.py
        --save-dir ./data/06_reporting/yolo/best/
        --dir-model ./data/04_models/yolo/best/
        --loglevel info
    deps:
      - ./scripts/model/yolo/build_manifest.py
      - ./data/04_models/yolo/best/
    outs:
      - ./data/06_reporting/yolo/best/

  export_best_model:
    cmd:
      - >-
        uv run python ./scripts/model/yolo/export.py
        --output-dir ./data/04_models/yolo-export/best/
        --model-dir ./data/04_models/yolo/best/
        --format onnx
        --device cpu
        --loglevel info
      - >-
        uv run python ./scripts/model/yolo/export.py
        --output-dir ./data/04_models/yolo-export/best/
        --model-dir ./data/04_models/yolo/best/
        --format ncnn
        --device cpu
        --loglevel info
    deps:
      - ./scripts/model/yolo/export.py
      - ./data/04_models/yolo/best/
    outs:
      - ./data/04_models/yolo-export/best/
