experiment_name: baseline
project: ./data/04_models/yolov8
task: detect
mode: train
model_type: yolov8n.pt
data: null
epochs: 50
patience: 10
batch: 16
imgsz:
  - 640
  - 480
save: true
save_period: -1
cache: false
device: null
workers: 8
name: null
exist_ok: false
pretrained: true
optimizer: SGD
verbose: true
seed: 0
deterministic: true
single_cls: true
rect: false
cos_lr: true
close_mosaic: 0
resume: false
amp: true
fraction: 1.0
profile: false
overlap_mask: true
mask_ratio: 4
dropout: 0
val: true
split: val
save_json: false
save_hybrid: false
conf: null
iou: 0.1
max_det: 300
half: false
dnn: false
plots: true
source: null
show: false
save_txt: false
save_conf: false
save_crop: false
show_labels: true
show_conf: true
vid_stride: 1
line_width: null
visualize: false
augment: true
agnostic_nms: false
classes: null
retina_masks: false
boxes: true
format: torchscript
keras: false
optimize: false
int8: false
dynamic: false
simplify: false
opset: null
workspace: 4
nms: false
learning_rate: 0.001
momentum: 0.937
weight_decay: 0.0001
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
pose: 12.0
kobj: 1.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0
copy_paste: 0
cfg: null
v5loader: false
tracker: botsort.yaml
